### ISSUE TITLE
Botão de Finalizar aparecendo apenas na última questão

### ISSUE THREAD

**Issue by jooaodias** [Minhacps/votacidade#105]
## **Aplicação**
A qual aplicação o problema está relacionado?

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Tipo de problema**

 
- Funcional
- Usabilidade

## **Descrição**
Quando o usuário responder 70% das questões, o botão de finalizar o questionário apenas está disponível na última questão e não aonde ele está.

### **Passos para reproduzir**
- Abre o site
- Abra o questionário
- Responda 70% das questões e pule até a última questão para ver o botão de finalizar

### **Resultado atual**
- Botão de finalizar apenas disponível na última questão

### **Resultado esperado**
- Botão de finalizar apresentado aonde o usuário estiver

**Comment by victormiguez** [comment]
@jooaodias podemos fechar essa issue?

**Comment by jooaodias** [comment]
tudo certo @victormiguez
