### ISSUE TITLE
Recuperação de senha

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votacidade#11]
> Como usuário, gostaria de mudar minha senha caso tenha esquecido, para poder acessar a aplicação.

Esqueci minha senha. Deve ser desenvolvido uma funcionalidade de recuperação de senha para os usuários.

**Comment by wab030** [comment]
@victormiguez boa noite. Vc acha que já pode adiantar um pouco isso?

**Comment by lguima** [comment]
Duplicado com #98
