### ISSUE TITLE
Liberação do indíce de afinidade. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#110]
## **Aplicação**
A qual aplicação a tarefa está relacionada?

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Descrição**
Cada cidade poderá ter um critério de lançamento do índice de afinidade. Portanto o match só deve ser habilitado se o critério for alcançado.

**Comment by lguima** [comment]
@wab030 isso foi feito com a flag `enableRanking`, certo?

**Comment by wab030** [comment]
Sim sim

Em sáb, 17 de out de 2020 09:51, Lucas Guima <notifications@github.com>
escreveu:
