### ISSUE TITLE
Incluir na página de cadastro o fundo da página de login.

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#111]
## **Aplicação**
A qual aplicação o problema está relacionado?

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Tipo de problema**
Estético.
- Layout

## **Descrição**
No cadastro do eleitor ou candidato não aparece um cabeçalho ou rodapé. 

### **Passos para reproduzir**
Entrar para cadastras um novo usuário.

### **Resultado atual**
Aparece uma tela somente com o cadastro. Esteticamente não fica muito legal. 
![Screenshot from 2020-08-25 13-25-58](https://user-images.githubusercontent.com/7780073/91201254-9aa33b00-e6d6-11ea-8a68-b1ae7abbb084.png)

### **Resultado esperado**
Informe o resultado que deveria acontecer.

### **Evidências**
Inclua evidências que possam ajudar a demonstrar o problema.

## **Issues relacionadas**
Informe as issues que são relacionadas.

*Ex.: Relacionada a #*

**Comment by victormiguez** [comment]
Resolvido no pull request https://github.com/Minhacps/votacidade-app/pull/26.
