### ISSUE TITLE
Mudar o label de email para e-mail no cadastro.

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#112]
## **Aplicação**
A qual aplicação o problema está relacionado?

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Tipo de problema**
Label

- Layout

## **Descrição**
Na tela de login o label para e-mail é E-mail. Na tela de cadastro é email. Substitui na tela de cadastro para e-mail para manter o padrão.

**Comment by victormiguez** [comment]
Resolvido no pull request Minhacps/votacidade-app#26.
