### ISSUE TITLE
Gravar a última questão do candidato quando clicar no botão finalizar. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#115]
## **Aplicação**
A qual aplicação o problema está relacionado?

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Tipo de problema**
Funcional

## **Descrição**
Quando o candidato(a) chega na última questão o sistema exige que ele clique em responder para gravar a questão mas isto não está claro. O que mai chama a atenção nessa tela é o botão finalizar. Provavelmente o candidato clicará no botão finalizar e o sistema não terá gravado a última questão. Uma alternativa seria fazer o botão Finalizar gravar a última questão também. 

### **Passos para reproduzir**
Responder o questionário, como candidato, até a última questão. 

### **Resultado atual**
O sistema não grava a última questão se o candidato não clicar em responder. 

### **Resultado esperado**
Uma ideia seria o botão finalizar gravar a última questão do candidato (a)

**Comment by victormiguez** [comment]
Resolvido no pull request https://github.com/Minhacps/votacidade-app/pull/26.
