### ISSUE TITLE
Barra de progresso não calcula

### ISSUE THREAD

**Issue by jooaodias** [Minhacps/votacidade#116]
## **Aplicação**
A qual aplicação o problema está relacionado?

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Tipo de problema**
Informe o tipo de problema

- Funcional

## **Descrição**
Barra de progresso apenas começa a aparecer quando da um rena página após abrir o Questionário

### **Passos para reproduzir**
- Abre o app
- Faça o login/cadastro
- Abra o questionário
- Veja a barra de progresso
- Atualize a página e veja a barra de progresso calculando

### **Resultado atual**
Respondi 2 questões
![print1](https://user-images.githubusercontent.com/52572698/91351932-71aaa500-e7bf-11ea-8aba-5f2313987918.png)

### **Resultado esperado**
![print2](https://user-images.githubusercontent.com/52572698/91352052-a6b6f780-e7bf-11ea-9d6d-c906c238ad92.png)

**Comment by victormiguez** [comment]
Resolvido com o PR https://github.com/Minhacps/votacidade-app/pull/25.
