### ISSUE TITLE
Incluir uma mensagem que o CNPJ é opcional nesse momento. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#123]
## **Aplicação**
A qual aplicação a tarefa está relacionada?

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Descrição**
Incluir uma mensagem dizendo que o CNPJ é opcional nesse momento.

**Comment by lguima** [comment]
@wab030 @jooaodias @victormiguez 
esta issue foi a inclusão da mensagem "Opcional enquanto não homologado" no campo?
