### ISSUE TITLE
Texto entrar com Twitter deveria estar branco e não preto. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#127]
## **Aplicação**
A qual aplicação a tarefa está relacionada?

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Descrição**
Alterar a cor do texto entrar com Twitter para branco.

**Comment by lguima** [comment]
@wab030 branco causa problema de contraste, foi um ponto que levantei quando o @degrecci implementou o login
