### ISSUE TITLE
Validar o campo número do candidato para aceitar somente números. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#128]
## **Aplicação**
A qual aplicação o problema está relacionado?

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Tipo de problema**
Funcional

## **Descrição**
Validar o campo número do candidato para aceitar somente números. 

### **Passos para reproduzir**
Digitar um texto no campo número do candidato(a)

### **Resultado atual**
Aceita texto.

### **Resultado esperado**
Exibir uma mensagem de erro quando for digitado texto.

**Comment by lguima** [comment]
Resolvido por Minhacps/votacidade-app#60
