### ISSUE TITLE
Monitoramento de acessos e uso

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votacidade#13]
Como Minha Campinas, eu gostaria de monitorar os acessos no site para gerar métricas.

**Comment by wab030** [comment]
Código para colocar no index.html


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-170993659-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-170993659-1');
</script>
