### ISSUE TITLE
Incluir algum tipo de destaque para a questão. (Por exemplo negrito)

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#132]
## **Aplicação**
A qual aplicação a tarefa está relacionada?

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Descrição**
Incluir algum tipo de destaque para a questão. (Por exemplo negrito)

**Comment by jooaodias** [comment]
desktop -> aumentar a fonte para 18px
