### ISSUE TITLE
Ajustar o design do menu para celular de acordo com a proposta da Amanda. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#138]
## **Aplicação**
A qual aplicação a tarefa está relacionada?

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Descrição**
Ajustar o design do menu para celular de acordo com a proposta da Amanda.

**Comment by degrecci** [comment]
Opa, acho que essa foi feita junto com o quadro de questões #117
