### ISSUE TITLE
Reuzir a margem direita do menu, na versão desktop, para ficar alinhado com a barra de progresso. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#144]
## **Aplicação**
- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Descrição**
Reuzir a margem direita do menu, na versão desktop, para ficar alinhado com a barra de progresso.

@degrecci vc pode dar uma olhada nisso? Valeu.

**Comment by victormiguez** [comment]
@degrecci já corrigimos esse problema, não precisa pegar essa issue.
