### ISSUE TITLE
Como usuário, gostaria de ler um resumo das minhas respostas antes de submeter meu questionário, para confirmar se não esqueci nenhuma questão.

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votacidade#15]
Confirmação ao usuário se ele deseja finalizar o questionário

**Comment by wab030** [comment]
Talvez a barra de progressão possa ter essa função também.

**Comment by jooaodias** [comment]
Ainda iremos fazer?

**Comment by wab030** [comment]
Acho que pode fechar. Creio que não vamos fazer.

Em sáb, 17 de out de 2020 09:47, João Aleixo <notifications@github.com>
escreveu:
