### ISSUE TITLE
Trocar o placeholder do e-mail no login e cadastro

### ISSUE THREAD

**Issue by jooaodias** [Minhacps/votacidade#154]
## **Aplicação**
A qual aplicação o problema está relacionado?

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Tipo de problema**
Informe o tipo de problema

- Digitação
- Usabilidade

## **Descrição**
- Alguns candidatos acabaram errando a escrita do e-mail no entrar e cadastrar

### **Passos para reproduzir**
- Abrir o app e ver o entrar e cadastrar

### **Resultado atual**
- O placeholder do e-mail está: Digite o seu e-mail

### **Resultado esperado**
- Alguma maneira que o usuário não se confunda, usando por exemplo: _exemplo@email.com_

### **Evidências**
![image](https://user-images.githubusercontent.com/52572698/94720665-238f4100-032b-11eb-8128-71b3f35c28b2.png)

**Comment by lguima** [comment]
Mas o placeholder foi o problema? O campo já valida o formato do e-mail, se a pessoa errou, foi por distração, o placeholder não vai mudar muita coisa.

**Comment by jooaodias** [comment]
Acompanhamos alguns erros de alguns candidatos, mais velhos, que tiveram dificuldade.. Não sei uma outra alternativa para evitar esses erros.

**Comment by lguima** [comment]
Tem que entender qual foi a dificuldade, se foi de entender que o campo era de e-mail, ou qual era o formato do e-mail?

**Comment by wab030** [comment]
Acho que o Guima está correto. Foi um caso somente. Seguimos assim.
