### ISSUE TITLE
Erro de permissão negada ao salvar a resposta de candidato(a)

### ISSUE THREAD

**Issue by lguima** [Minhacps/votacidade#166]
## **Aplicação**

- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Tipo de problema**

- Integração

## **Descrição**
Ao salvar a resposta de um(a) candidato(a), um erro de permissão negada é lançado.

### **Passos para reproduzir**
- Acessar o app como candidato(a)
- Acessar o questionário
- Responder uma questão

### **Resultado atual**
Um erro de permissão negada é lançado.

### **Resultado esperado**
Nenhum erro deveria ser lançado.

### **Evidências**

**Ambiente de desenvolvimento**
![permission-denied-console](https://user-images.githubusercontent.com/1562097/95764110-64217f80-0c86-11eb-9eb2-67b3f827c9fe.PNG)

**Ambiente local**
![permission-denied](https://user-images.githubusercontent.com/1562097/95764122-684d9d00-0c86-11eb-93c7-42ffee02e859.PNG)

**Comment by victormiguez** [comment]
Posso investigar esse problema mais tarde, está acontecendo em dev e prod?

**Comment by wab030** [comment]
Em dev

User: campinascandidate@gmail.com
Ifsp@1234

Tenta incluir uma justificativa na 1 questão

Em seg, 12 de out de 2020 19:51, Victor Miguez <notifications@github.com>
escreveu:

**Comment by victormiguez** [comment]
O problema estava acontecendo porque o realtime database de recife estava desativado.
Agora ativamos o database e o erro não acontece mais.
