### ISSUE TITLE
Criação do logotipo Vota Cidade

### ISSUE THREAD

**Issue by lguima** [Minhacps/votacidade#23]

**Comment by mandyellow** [comment]
Resultado da enquete do domínio:
![image](https://user-images.githubusercontent.com/30158643/82448282-e3b47500-9a7f-11ea-9fa6-eb5232c27ddf.png)

**Comment by mandyellow** [comment]
Boa tarde galera,

Fiz aqui uma proposta para o logo do projeto. Como havia comentado, fiz duas versões:
- Um logo principal, que pode ser usado todos os anos
- Um logo secundário, variação desse primeiro que ficou como "Vota Cidade"

Segue uma prévia, mas o PDF no final está mais completo:
![image](https://user-images.githubusercontent.com/30158643/82737828-11acea00-9d0a-11ea-80c4-5dc10adeb1de.png)

As cores seguem como roxo e amarelo, como as cores de dois anos atrás, mas mais vivas, com mais contraste. Acredito, pelas minhas pesquisas, que essas cores criam um contraste legal também para daltônicos, então é um bom primeiro passo para deixarmos o site/app mais acessíveis.

PDF:
[apresentação-logo.pdf](https://github.com/Minhacps/votacidade/files/4672308/apresentacao-logo.pdf)

**Comment by lguima** [comment]
massa demais! demorei um pouco pra me ligar na imagem do match de opiniões, mas dps fez mto sentido! huah

ficou só uma dúvida quanto às opções, a ideia é a gente escolher uma delas ou usaremos as duas?

seria legal ter isso claro até pra colocar nos critérios de aceite da issue

**Comment by mandyellow** [comment]
A minha ideia é, esse ano, usar o "Vota Cidade" mesmo, mas como não dá para usar "Vota Cidade" daqui dois anos, achei legal propor uma marca base para podermos trocar esse "Cidade" por outra palavra.

De qualquer forma, vamos ter uma reunião sobre a parte de comunicação do projeto para apresentar essa proposta e alinharmos essas questões hehe

**Comment by guiluchesi** [comment]
Gostei que já tá até na cor do Gatsby 😂

**Comment by mandyellow** [comment]
Apenas para atualizar a situação da marca:

No dia 29 de Maio (sexta) tivemos o GT de Comunicação, onde o logo foi apresentado aos integrantes. Com a aprovação desses integrantes, dia 30 de Maio (sábado), apresentamos o logo para o GT Geral.

- No geral, as reações foram bastante positivas sobre a marca.
- Logo "Vota" ficará como base para usarmos todos os anos.
- Esse ano usaremos a marca "Vota Cidade" de maneira unificada para todas as cidades, afim de construir uma marca forte, que seja fácil de associar e de divulgar para a imprensa, além de facilitar a adesão de novas cidades (eventualmente, nos próximos anos).
- Para trazer o projeto para mais perto de cada cidade, foi decidido que ao invés de usarmos o nome das cidades junto ao logo, vamos explorar fotos, linguajar, etc nas postagens/divulgações. Sendo assim, toda a divulgação vai rodar em volta da marca "Vota Cidade".

Acredito que seja isso. Se alguém tiver alguma dúvida, tem as atas das duas reuniões no drive do projeto e, além disso, me coloco à disposição para mais esclarecimentos.
