### ISSUE TITLE
Criação do wireframe da Landing Page

### ISSUE THREAD

**Issue by mandyellow** [Minhacps/votacidade#24]
## Critérios de aceite
- Considerar a adequação a dispositivos móveis em primeiro lugar (mobile first)
- Conter opção de coleta de e-mail para notificação do lançamento da ferramenta
- Conter a explicação de como funciona a classificação de afinidade proposta
  - Abordar sobre as questões, quantidade e temas;
  - Abordar o cálculo da afinidade entre eleitores(as) e candidatos(as)
  - Abordar a possibilidade acessar a ficha individual de cada candidato(a) e suas respostas
  - Abordar a preocupação a privacidade dos usuários e a opção de resposta anônima
- Conter a descrição do objetivo da iniciativa
- Conter link para captação de recursos para manter o projeto/organização
- Conter a lista com nome e foto dos participantes da execução da iniciativa
- Conter a lista com nome e logotipo das organizações envolvidas na iniciativa
- Conter notícias educacionais relacionadas à política
- Conter link para as redes sociais

**Comment by mandyellow** [comment]
Desenhei a base do wireframe para começarmos o desenvolvimento da landingpage e do conteúdo em si. Minha ideia é centralizar as 5 cidades em um único site, tendo em mente que os conteúdos sugeridos serão do projeto como um todo. Desenhei modelo desktop e mobile com sugestões dos temas que acredito serem importantes de abordarmos.

Link visualização XD (2 páginas): https://xd.adobe.com/view/5fe836e4-6eaa-4ece-545e-0e75108b8936-29d9/

Para os que não são muito familiarizados com o visualizador do XD, e também para documentar o progresso inicial caso o link seja atualizado para uma nova versão após ajustes, deixo também os JPGs. 

JPG desktop:
![Inicial](https://user-images.githubusercontent.com/30158643/82220052-86d88380-98f4-11ea-9a9c-96090e6f7fd5.jpg)

JPG mobile:
![Inicial-1](https://user-images.githubusercontent.com/30158643/82220097-95bf3600-98f4-11ea-8186-f6d4b7a39b61.jpg)

**Comment by mandyellow** [comment]
@wab030 @marcelonisida segue para avaliação e também para começarmos a pensar nos conteúdos

**Comment by lguima** [comment]
oi @mandyellow, se eu puder opinar também :)

curti demais a disposição e as sugestões de conteúdo, faz muito sentido!

um detalhe que percebi é o alinhamento dos títulos das seções (como funciona, conheça o projeto e eleições 2020), a ideia é centralizar ou manter à esquerda?

outro ponto é o alinhamento ao centro de parágrafos (texto dos boxes e descrição da iniciativa), não é uma boa prática de UX pq dificulta a leitura, à esquerda é mais recomendado

e quanto à sugestão para o botão "Apoie o projeto", tem apenas um detalhe, se criarmos uma nova página, deixará de ser uma landing page (página única)

o que não deixa de ser uma alternativa viável, mas daí talvez fosse melhor a gente transformar as seções em páginas

o que acha?

---

e sobre a coluna da atividade enquanto a gente avalia e opina, lembro de termos combinado de deixar em "In Progress", pq essa etapa faz parte do desenvolvimento de um wireframe, vai e vem para avaliação, mas isso é um progresso ainda

em "On hold", no meu entendimento, vc poderia colocar se faltasse informação, e te impedisse de continuar

**Comment by mandyellow** [comment]
Oi @lguima! Todo mundo pode, e é legal que comentem, principalmente se tiverem embasamento técnico. Gosto principalmente para meu aprimoramento pessoal! 😄 

Os títulos eu tinha misturado mesmo haha Mas acho que podemos centralizar todos e seguir com o texto alinhado à esquerda, para manter as boas práticas.

Confesso que tinha esquecido o fato de ser uma Landing Page. Sugeri fazer isso para a página não ficar muito extensa com conteúdos secundários, mas que não deixam de ser importantes. Mas fico aberta a sugestões e acredito que será mais fácil definir isso depois de falar com o pessoal que vai definir o conteúdo mesmo haha

-

Opa, ok! Fiquei na dúvida se isso era parte do processo ou se deveria ficar 'on hold' por conta da aprovação. Obrigada!

**Comment by wab030** [comment]
Gostei muito Amanda. Ficou muito bem organizado e clean. 
A minha dúvida é só em relação ao conteúdo político. Se deve vir logo no começo ou no final. Mas podemos trocar uma ideia na reunião de amanhã.

**Comment by lguima** [comment]
Atualizei o comentário inicial da issue com os "Critérios de aceite", que são itens que definirão quando a issue pode ser considerada completa, basicamente já tem tudo o que a Amanda contemplou, mas é bom a gente ter como documentação.

@mandyellow @wab030

**Comment by mandyellow** [comment]
Levando em consideração os pontos apresentados na reunião de quarta-feira (20) em que decidimos separar as páginas do site, redesenhei o wireframe Desktop.

Acredito que, dos conteúdos discutidos, só faltou a página "Dicionário Político" mas como isso ainda está pendente, acredito que podemos focar os esforços no que já é certo para por o quanto antes esse site no ar.

Link (3 páginas): https://xd.adobe.com/view/cb813ff4-d120-46cf-5768-175558e82822-bdb0/

**Comment by mandyellow** [comment]
Olá, como o desenvolvimento do site já começou, organizei o wireframe para podermos fechar essa issue e trabalhar em cima do protótipo de alta fidelidade.

Link atualizado (desktop e mobile): https://xd.adobe.com/view/17e9961b-e53a-48d1-549a-5f98f592caec-61d8/

Telas em JPG: [Vota-Wireframe.zip](https://github.com/Minhacps/votacidade/files/4805764/Vota-Wireframe.zip)
