### ISSUE TITLE
Listagem de pessoas que contribuíram

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#28]
O site deve possuir uma seção ou uma página com listagem das pessoas que participaram do desenvolvimento. Deve conter fotos dos participantes.

**Comment by lguima** [comment]
@wab030 se puder incluir o link para aquela pasta com as fotos, não encontrei no Drive do Vota

**Comment by wab030** [comment]
https://drive.google.com/drive/u/0/folders/1Wzo-eEyjyLo1CWBIbR0mPW8KyhDet1rT
