### ISSUE TITLE
Como eleitor, gostaria de ouvir as descrições das questões via audio descrição.

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votacidade#3]
- [ ] Incluir áudio na descrição das questões.
- [ ] Inserir VLibras

**Comment by wab030** [comment]
@jooaodias Você dar uma olhada junto com a Vanessa para ver qual tecnologia vamos utilizar?

**Comment by jooaodias** [comment]
Pode deixar, estamos pesquisando sobre como iremos adicionar essas funcionalidades.

**Comment by wab030** [comment]
@jooaodias Você acha que vai rolar essa funcionalidade.?

**Comment by jooaodias** [comment]
Vou pesquisar se é bom ter essa funcionalidade mesmo.

**Comment by wab030** [comment]
@jooaodias Algo avançou aqui?

**Comment by lguima** [comment]
Áudio descrição não serve para texto, apenas para conteúdo audiovisual ou imagens estáticas, como fi­lmes, fotografi­as, peças de teatro, entre outros.

_Referência: [O que é audiodescrição?](https://www.fundacaodorina.org.br/blog/o-que-e-audiodescricao)_

**Comment by jooaodias** [comment]
Então podemos fechar essa issue, pois as imagens já estão com o **_alt_**  e o leitor de tela já pega as questões e as questões (só fazer um teste depois disso para ver se está certinho)
