### ISSUE TITLE
Traduzir o README do Gatsby

### ISSUE THREAD

**Issue by lguima** [Minhacps/votacidade#45]
O Gatsby gera uma documentação bem legal de start do projeto no read.me, mas está em inglês. Seria legal traduzirmos para ficar mais acessível a todos.

**Comment by lguima** [comment]
@guiluchesi trouxe a issue para cá para centralizarmos neste repositório

**Comment by guiluchesi** [comment]
Cara, vi que colocou um read.me resumido lá, achei legal. Mas como tava sem nada pra fazer e a task ainda tava aberta, traduzi. Veja lá, e quem mais quiser ver também haha, se acha que fica muito grande ou se vale a pena o merge da pr.

https://github.com/Minhacps/votacidade-site/pull/10

**Comment by lguima** [comment]
@guiluchesi então, eu tinha movido os detalhes de instalação pra um arquivo à parte (`.github/INSTALLING.md`)

aproveitando o cenário, sugiro a gente trabalhar com fork, pq vi que vc aplicou o gitflow dentro do próprio repositório, mas acabou sobrescrevendo oq eu fiz, pq vc saiu da `develop` e ela não tava atualizada com a `master`

o que acha?

**Comment by guiluchesi** [comment]
Acho que os branchs já dão conta. Eu que me não tinha visto que tinha movido o read.me do Gatsby pra esse installing e acabei duplicando o conteúdo.

Não sobrescreveu, eu troquei o h1 em formato html e por MD mas o conteúdo que vc tinha escrito eu mantive, só juntei com o texto do Gatsby traduzido. Vou fechar a PR e mandar a tradução pro lugar certo e sucesso.

**Comment by lguima** [comment]
ah, pode crer, boa!
