### ISSUE TITLE
Formulário para coleta de e-mail para o lançamento do Vota Cidade

### ISSUE THREAD

**Issue by guiluchesi** [Minhacps/votacidade#56]
Como organização Minha Campinas eu gostaria de captar interessados pela plataforma e que queiram ser avisados do lançamento.

---

Campos para captura
- Nome
- E-mail
- Se é pré-candidato(a)

-----

Formulário deve ser integrado com Mailchimp

**Comment by guiluchesi** [comment]
Fica faltando apenas a URL do formulário final para funcionamento integral dessa funcionalidade

**Comment by lguima** [comment]
Fechando essa issue pois o pull request já foi mergeado.

Minhacps/votacidade-site#14
