### ISSUE TITLE
Criar um favicon para o projeto. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#58]
## **Aplicação**

- [X] Site - [`Minhacps/votacidade-site`](https://github.com/Minhacps/votacidade-site)
- [X] App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

**Comment by mandyellow** [comment]
@wab030 veja se isso resolve

[favicon_io.zip](https://github.com/Minhacps/votacidade/files/4786540/favicon_io.zip)

**Comment by wab030** [comment]
@mandyellow Estou fechando esse request.
