### ISSUE TITLE
O usuário pode pular questões que não queira responder.

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#61]
O usuário pode pular no máximo 10 questões. Ele deve responder no mínimo 20 questões para conseguir gerar o índice de afinidade. 

Critério de aceite: Possibilidade de pular uma questão.

**Comment by victormiguez** [comment]
@wab030 podemos fechar essa issue?

**Comment by wab030** [comment]
Sim sim


Em qui, 15 de out de 2020 22:12, Victor Miguez <notifications@github.com>
escreveu:
