### ISSUE TITLE
Falta de contraste no elemento de licenciamento no Footer

### ISSUE THREAD

**Issue by jooaodias** [Minhacps/votacidade#71]
## **Aplicação**

- [X] Site - [`Minhacps/votacidade-site`](https://github.com/Minhacps/votacidade-site)
- [ ] App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Tipo de bug**

- [X] Accessibilidade
- [ ] Automação
- [ ] Digitação
- [ ] Funcional
- [ ] Interrupção
- [ ] Layout
- [ ] Performance
- [ ] Usabilidade
- [ ] Outro (Especifique, por favor)

## **Descrição**
* Problemas de contraste na tags de link de licenciamento no Footer

### **Passos para reproduzir**
* Abra a página inicial
* Inspecione o link de licenciamento no Footer

### **Resultado atual**
* Falta de contraste no link

### **Resultado esperado**
* Não ter problemas de contraste no link

### **Evidências**
![footer](https://user-images.githubusercontent.com/52572698/85582654-fc322500-b613-11ea-812e-ee340f37ca58.png)

**Comment by wab030** [comment]
![image](https://user-images.githubusercontent.com/7780073/85852243-92865800-b786-11ea-9750-45e0f2138627.png)
