### ISSUE TITLE
Definir a Política de Privacidade e de Cookies do Vota Cidade

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#72]
## **Aplicação**
A qual aplicação a estória está relacionada?

- Site - [`Minhacps/votacidade-site`](https://github.com/Minhacps/votacidade-site)
- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Critérios de aceite**
- Ter a Política de Privacidade escrita e revisada.
- Ter a Política de Cookies escrita e revisada.

## **Tarefas**
- [ ] Escrever a Política de Privacidade
- [ ] Escrever a Política de Cookies
- [ ] Revisar a Política de Privacidade
- [ ] Revisar a Política de Cookies

**Comment by lguima** [comment]
Documentos para a construção:
* [Política de Privacidade](https://docs.google.com/document/d/1GgfQE26t5ewxtQBaUZsGi-l0J1XLDEOI17BACBjApHk)
* [Política de Cookies](https://docs.google.com/document/d/1QOYb6sbc8B9it0vq6dXqdIcE5u24_dlsDk5a2svLUVA)
