### ISSUE TITLE
Alterar o destino do CTA para o formulário do Mailchimp

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade#89]
## **Aplicação**

- Site - [`Minhacps/votacidade-site`](https://github.com/Minhacps/votacidade-site)

## **Descrição**
Alterar o link para envio dos dados do CTA do site para o form abaixo:

<form action="https://gmail.us10.list-manage.com/subscribe/post?u=145b9e413ba4cf4f138b21c21&amp;id=956113fd98" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>

**Comment by luchesigui** [comment]
@wab030 não tem link nenhum haha se quiser me mandar no privado também, fica a vonts :P

**Comment by wab030** [comment]
Tinha certeza de ter colocado aqui rsss

form action="https://gmail.us10.list-manage.com/subscribe/post?u=145b9e413ba4cf4f138b21c21&amp;id=956113fd98" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate

**Comment by wab030** [comment]
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://gmail.us10.list-manage.com/subscribe/post?u=145b9e413ba4cf4f138b21c21&amp;id=956113fd98" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-CANDIDATO">Pré Candidato (a) </label>
	<input type="text" value="" name="CANDIDATO" class="" id="mce-CANDIDATO">
</div>
<div class="mc-field-group">
	<label for="mce-CIDADE">Cidade </label>
	<input type="text" value="" name="CIDADE" class="" id="mce-CIDADE">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_145b9e413ba4cf4f138b21c21_956113fd98" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='CANDIDATO';ftypes[1]='text';fnames[2]='CIDADE';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

**Comment by wab030** [comment]
Na verdade o link sempre esteve lá rssss. Como coloquei no formato de tag ele desaparece na visualização.

**Comment by luchesigui** [comment]
@wab030 feito.

**Comment by lguima** [comment]
@wab030 vou manter a issue aberta até finalizar o ajuste do conteúdo da mensagem de sucesso e de erro do Mailchimp
