### ISSUE TITLE
Barra de Progresso

### ISSUE THREAD

**Issue by luchesigui** [Minhacps/votacidade#90]
![image](https://user-images.githubusercontent.com/5860206/88356650-eca31a80-cd3e-11ea-9356-56fb6d534cff.png)
![image](https://user-images.githubusercontent.com/5860206/88356686-08a6bc00-cd3f-11ea-9e04-76e1ab9bf9b7.png)
![image](https://user-images.githubusercontent.com/5860206/88356693-10666080-cd3f-11ea-9181-7983c130de54.png)

https://xd.adobe.com/view/d8662167-c896-4f6d-82e2-e2bdcc426f6a-8d35/screen/b1837bd0-0c05-47d5-bad9-7edeb31aaef4/

**Comment by victormiguez** [comment]
Essa issue vai ser resolvida com esse PR: https://github.com/Minhacps/votacidade-app/pull/13

**Comment by luchesigui** [comment]
Que coisa não?! 🤣
